version: "3.9"
services:
  mongodb:
    image: mongo:4.4
    container_name: my-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  #node:
  #  build: ./backend
  #  container_name: my-node-app
  #  restart: always
  #  depends_on:
  #    - mongodb
  #  environment:
  #    - MONGO_URL=mongodb://root:example@mongodb:27017/myapp
  #  ports:
  #    - "5000:5000"
  #react:
  #  build: ./frontend
  #  container_name: my-react-app
  #  restart: always
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    - REACT_APP_API_URL=http://node:5000
volumes:
  mongodb-data:
